[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rivgraph"
version = "0.5.0"
description = "Python package for extracting and analyzing river networks from remote sensing imagery."
authors = [
  { name = "Jon Schwenk", email = "jonschwenk@gmail.com" }
]

[tool.setuptools.packages.find]
where = ["."]
include = ["rivgraph", "rivgraph.*"]