# -*- coding: utf-8 -*-

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# Since we aren't installing package here, we mock imports of the dependencies.

import os
import sys

# path to repo-head
sys.path.insert(0, os.path.abspath('../..'))

# get current version
from rivgraph import __version__

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.doctest',
              'sphinx.ext.autosummary',
              'sphinx.ext.todo',
              'sphinx.ext.coverage',
              'sphinx.ext.mathjax',
              'sphinx.ext.viewcode',
              'sphinx.ext.githubpages',
              'sphinx.ext.napoleon',
              'sphinx_gallery.gen_gallery']

# gallery configuration
sphinx_gallery_conf = {
	'examples_dirs': 'gallery_source',  # path to gallery scripts
	'gallery_dirs': 'gallery',  # pvath to where to save gallery output
	'remove_config_comments': True,
	'download_all_examples': False,
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'RivGraph'
copyright = '2020, J. Schwenk & J. Hariharan'
author = 'J. Schwenk & J. Hariharan'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {
    "logo_only": True,
    "display_version": True,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_logo = "../logos/rg_logo_full.png"

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'RivGraphdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'RivGraph.tex', 'RivGraph Documentation',
     'J. Schwenk', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'rivgraph', 'RivGraph Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'RivGraph', 'RivGraph Documentation',
     author, 'RivGraph', 'Tools for working with channel network masks.',
     'Miscellaneous'),
]

# -- Options for linkcheck -------------------------------------------

# Some links are throwing 403s for unknown reasons; we simply skip checking them here.
linkcheck_ignore = [r'https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2014WR016577%4010.1002/%28ISSN%291944-7973.CONART1',
		    r'https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2014WR016604',
		    r'https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016EA000196',
		    r'https://pubs.geoscienceworld.org/gsa/geology/article/47/3/263/568705/High-curvatures-drive-river-meandering',
		    r'https://github.com/Unidata/MetPy#contributing',
		    r'http://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2008GL033963',
		    r'https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2008GL033963',
		    r'https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2019WR026867',
		    r'https://pubs.geoscienceworld.org/gsa/geology/article/doi/10.1130/G49935.1/614344/Quantitative-relationships-between-river-and',
		    r'https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2022GL099681',
		    r'https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2022GL097897',
		    r'https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2022GL098284',
            r'https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2022GL102201'
		    ]
